### ISSUE TITLE
Problem with encoding

### ISSUE THREAD

**Issue by papoteur-mga** [robertsdotpm/p2pd#1]
I'm exploring this promising library.
But, following the basics:
```
>>> from p2pd import *
>>> netifaces = await init_p2pd()
>>> ifs = await load_interfaces(netifaces=netifaces)
Traceback (most recent call last):
  File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
  File "/home/yves/.local/lib/python3.8/site-packages/p2pd-2.3.2-py3.8.egg/p2pd/interface.py", line 486, in load_interfaces
    ifs = await filter_trash_interfaces(netifaces)
  File "/home/yves/.local/lib/python3.8/site-packages/p2pd-2.3.2-py3.8.egg/p2pd/interface.py", line 452, in filter_trash_interfaces
    results = await asyncio.gather(*tasks)
  File "/home/yves/.local/lib/python3.8/site-packages/p2pd-2.3.2-py3.8.egg/p2pd/interface.py", line 444, in worker
    r = await is_internet_if(if_name)
  File "/home/yves/.local/lib/python3.8/site-packages/p2pd-2.3.2-py3.8.egg/p2pd/route_table.py", line 200, in is_internet_if
    return await linux_is_internet_if(if_name)
  File "/home/yves/.local/lib/python3.8/site-packages/p2pd-2.3.2-py3.8.egg/p2pd/route_table.py", line 176, in linux_is_internet_if
    table = await get_route_table(af)
  File "/home/yves/.local/lib/python3.8/site-packages/p2pd-2.3.2-py3.8.egg/p2pd/route_table.py", line 100, in get_route_table
    return await linux_get_route_table(af)
  File "/home/yves/.local/lib/python3.8/site-packages/p2pd-2.3.2-py3.8.egg/p2pd/route_table.py", line 54, in linux_get_route_table
    out = await cmd(cmd_buf, timeout=4)
  File "/home/yves/.local/lib/python3.8/site-packages/p2pd-2.3.2-py3.8.egg/p2pd/cmd_tools.py", line 180, in cmd
    return to_s(stdout)
  File "/home/yves/.local/lib/python3.8/site-packages/p2pd-2.3.2-py3.8.egg/p2pd/utils.py", line 92, in <lambda>
    to_s = lambda x: x if type(x) == str else x.decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 25: ordinal not in range(128)

```
This is probably linked to how my system is configured, but I don't know what the `stdout` is expected to provide.

**Comment by papoteur-mga** [comment]
What is the output of `route`:
```
route -4
Table de routage IP du noyau
Destination     Passerelle      Genmask         Indic Metric Ref    Use Iface
default         lan.home        0.0.0.0         UG    600    0        0 wlp2s0
192.168.1.0     0.0.0.0         255.255.255.0   U     600    0        0 wlp2s0
```

```
route -6
/proc/net/ipv6_route: Aucun fichier ou dossier de ce type
INET6 (IPv6) pas configuré sur ce système.
```

**Comment by robertsdotpm** [comment]
I think it's because you're using a local that uses non-ascii characters. Will push a fix for this later today. Thanks for trying the software out!

**Comment by papoteur-mga** [comment]
The problem can be solved with the prefix "LC_ALL=C " before /usr/bin/route commande :+1: https://github.com/robertsdotpm/p2pd/blob/a758d89cf16843c1d65eba876e5975a1968525d2/p2pd/route_table.py#L34
And here:
https://github.com/robertsdotpm/p2pd/blob/a758d89cf16843c1d65eba876e5975a1968525d2/p2pd/route_table.py#L53

**Comment by robertsdotpm** [comment]
Possibly fixed now.

**Comment by robertsdotpm** [comment]
I added a change to try make the string encoding more consistent but I may need to also go with your suggestion.
